### PR TITLE
Add allowable data-selectik override in options

### PR DESCRIPTION
**Pull request by philpalmieri**
Screenshot_1_31_13_8_02_PM
skitch

Hi,

I came across the need for this override - here is the use case:

Need formatted line breaks in value ie: < option value="long option" >Long < br / > Option< /option > so that the selectik version shows the html BR..  problem is, on an iOS device, it overrides the text / formatting and show the <br /> as plain text in the selection.

Additionally, if i put the BR in the value, or leave it out, then once an option is selected, it shows condensed in the selected state...  Lastly, if i put the BR in the value, it gets submitted - which i don't want

### CODE REVIEW

**Comment by philpalmieri** [comment]
I did not update the minified version....

**Comment by Brankub** [comment]
Pretty good idea. I'll check this in the coming days.

**Comment by Brankub** [comment]
Please simplify your code in pull request like this:

<pre><code>_generateHtml: function(){
    this.$collection = this.$cselect.children();
    var html = '';
    for (var i = 0; i &lt; this.$collection.length; i++){
        var $this = $(this.$collection[i]);
        html += '&lt;li class="'+ ($this.attr('disabled') === 'disabled' ? 'disabled' : '') +'" data-value="'+$this[0].value+'"&gt;'+($this.data('selectik') ? $this.data('selectik') : $this[0].text)+'&lt;/li&gt;';
    };
    return html;
},</code></pre>

After changes I will accept it and change minified version, demo page and help text.

**Comment by Brankub** [comment]
Hi Phil,

I mean this code, same in my last comment:

_generateHtml: function(){
    this.$collection = this.$cselect.children();
    var html = '';
    for (var i = 0; i < this.$collection.length; i++){
        var $this = $(this.$collection[i]);
        html += '<li class="'+ ($this.attr('disabled') === 'disabled'
? 'disabled' : '') +'"
data-value="'+$this[0].value+'">'+($this.data('selectik') ?
$this.data('selectik') : $this[0].text)+'</li>';
    };
    return html;
},

So you can replace previous whole method by mentioned above.

Best regards,
Ivan

**Comment by Brankub** [comment]
How is this?

 var textOption = ($this.attr('data-selectik')) ?
$this.attr('data-selectik') : $this[0].text;

*textOption = ($this has attribute ('data-selectik')) ? true : false;

Conditional Operator
http://www.w3schools.com/js/js_comparisons.asp

**Comment by philpalmieri** [comment]
sorry - didn't realize you got pinged on each reply..  i was working on a replay, $this is a jquery object, so attr() will return FALSE if no match..

**Comment by Brankub** [comment]
Thank you for you addition. Help/other files were changed.

**Pull request merged**
